AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Example of building via Templates

Parameters:
  DeploymentStageName:
    Description: The name of the stage for deplyment
    Type: String
    Default: api
  TargetPort:
    Description: the port that localstack runs on
    Type: String
    Default: "4566"
  TargetHost:
    Description: The host to target
    Type: String
    Default: host.docker.internal
Resources:
  SamplesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Samples
      AttributeDefinitions:
        - AttributeName: profile_key
          AttributeType: S
      KeySchema:
        - AttributeName: profile_key
          KeyType: HASH
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true